import Quickshell
import Quickshell.Io
import QtQuick
import QtQuick.Controls
import Qt5Compat.GraphicalEffects
import Qt.labs.folderlistmodel
import Quickshell.Wayland

PanelWindow {
    id: main
    implicitHeight: Screen.height
    implicitWidth: Screen.width
    color: "transparent"
    property int speed: 5000
    property string currentImagePath: ""
    property bool bgToggle: false

    anchors {
        top: true
        bottom: true
        left: true
        right: true
    }

    aboveWindows: true
    exclusionMode: "Ignore"
    exclusiveZone: 1

    WlrLayershell.layer: WlrLayer.Overlay
    WlrLayershell.keyboardFocus: WlrKeyboardFocus.Exclusive

    readonly property var defaultVideoExtensions: ["mp4", "webm", "mov", "avi", "mkv", "gif", "m4v", "flv", "wmv", "mpeg", "3gp"]
    readonly property var videoExtensions: (configs.video_extensions && configs.video_extensions.length > 0)
        ? configs.video_extensions
        : defaultVideoExtensions

    Component.onCompleted: {
        Quickshell.execDetached(["bash", Quickshell.shellPath("cache.sh"), Quickshell.shellDir]);
    }

    FileView {
        path: Quickshell.shellPath("config.json")
        watchChanges: true
        onFileChanged: reload()

        JsonAdapter {
            id: configs
            property string wallpaper_path
            property string cache_path
            property int number_of_pictures
            property string border_color
            property var video_extensions: []
        }
    }

    FileView {
        id: activeWallpaperFile
        path: Quickshell.env("HOME") + "/.cache/hyprquickpaper/current_wallpaper"
        watchChanges: false
    }

    FolderListModel {
        id: folderModel
        folder: "file://" + configs.wallpaper_path.replace("~", Quickshell.env("HOME"))
        showDirs: false
        nameFilters: ["*.png", "*.jpg", "*.jpeg"].concat(
            main.videoExtensions.map(function(ext) { return "*." + ext; })
        )
        sortField: FolderListModel.Name
    }

    function isVideoFile(fileName) {
        if (!fileName) return false;
        const lower = fileName.toLowerCase();
        for (let i = 0; i < videoExtensions.length; i++) {
            if (lower.endsWith("." + videoExtensions[i])) return true;
        }
        return false;
    }

    // Expands ~ and guarantees a trailing slash so concatenation with a
    // fileName never produces a broken "...folderimage.png" path.
    function normalizedPath(rawPath) {
        let p = rawPath.replace("~", Quickshell.env("HOME"))
        if (!p.endsWith("/")) p += "/"
        return p
    }

    // For videos, resolves to the cached .jpg thumbnail generated by
    // cache.sh, since QML Image cannot render the .mp4/.webm itself.
    // Used by the picker cards, which want a small fast-to-decode file.
    function getThumbnailSource(fileName) {
        if (!fileName) return "";
        let thumbnailFileName = fileName;
        if (isVideoFile(fileName)) {
            const lastDot = fileName.lastIndexOf(".");
            if (lastDot > 0) {
                thumbnailFileName = fileName.substring(0, lastDot) + ".jpg";
            }
        }
        return "file://" + normalizedPath(configs.cache_path) + thumbnailFileName;
    }

    // High-quality still extracted from a video, used only for the
    // full-screen background preview. The small .jpg thumbnail is still
    // what the picker cards use — decoding a 4K jpg for every card at
    // once would undo the picker's startup performance.
    function getVideoPreviewSource(fileName) {
        if (!fileName) return "";
        const lastDot = fileName.lastIndexOf(".");
        let baseName = fileName;
        if (lastDot > 0) baseName = fileName.substring(0, lastDot);
        return "file://" + normalizedPath(configs.cache_path) + baseName + ".hq.jpg";
    }

    function updateBackground() {
        if (folderModel.count === 0) return
        const fileName = folderModel.get(pathView.currentIndex, "fileName")

        // For images: full-quality source from wallpaper_path.
        // For videos: the .hq.jpg extracted by cache.sh, which is
        // native-resolution (up to 3840 wide) instead of the small
        // picker thumbnail.
        let fullPath
        if (isVideoFile(fileName)) {
            fullPath = getVideoPreviewSource(fileName)
        } else {
            fullPath = "file://" + normalizedPath(configs.wallpaper_path) + fileName
        }
        currentImagePath = fullPath
        if (!bgToggle) {
            bgImageB.source = fullPath
            bgToggle = true
        } else {
            bgImageA.source = fullPath
            bgToggle = false
        }
    }

    // -----------------------------------------------------
    // LOSSLESS FULL-QUALITY BACKGROUND
    // -----------------------------------------------------
    Item {
        id: backgroundLayer
        anchors.fill: parent

        Image {
            id: bgImageA
            anchors.fill: parent
            fillMode: Image.PreserveAspectCrop
            asynchronous: true
            cache: false
            smooth: true
            opacity: bgToggle ? 0.0 : 1.0
            Behavior on opacity { NumberAnimation { duration: 350; easing.type: Easing.InOutQuad } }

            onStatusChanged: {
                if (status === Image.Error) {
                    console.log("BG LOAD FAILED (bgImageA):", source)
                }
            }
        }

        Image {
            id: bgImageB
            anchors.fill: parent
            fillMode: Image.PreserveAspectCrop
            asynchronous: true
            cache: false
            smooth: true
            opacity: bgToggle ? 1.0 : 0.0
            Behavior on opacity { NumberAnimation { duration: 350; easing.type: Easing.InOutQuad } }

            onStatusChanged: {
                if (status === Image.Error) {
                    console.log("BG LOAD FAILED (bgImageB):", source)
                }
            }
        }
    }

    // -----------------------------------------------------
    // UNIFORM-HEIGHT BOTTOM DOCK WITH CURVED CORNERS
    // -----------------------------------------------------
    PathView {
        id: pathView
        anchors.fill: parent
        focus: true
        interactive: false

        model: folderModel
        pathItemCount: 15
        preferredHighlightBegin: 0.5
        preferredHighlightEnd: 0.5

        onCurrentIndexChanged: updateBackground()

        Timer {
            id: initTimer
            interval: 50
            repeat: false
            onTriggered: {
                if (folderModel.count === 0) return

                let rawText = activeWallpaperFile.text() ? activeWallpaperFile.text() : ""
                let activePath = rawText.trim()
                let matchedIndex = -1

                if (activePath.length > 0) {
                    for (let i = 0; i < folderModel.count; i++) {
                        let itemPath = folderModel.get(i, "filePath")
                        if (itemPath === activePath) {
                            matchedIndex = i
                            break
                        }
                    }
                }

                if (matchedIndex === -1) {
                    matchedIndex = Math.floor(folderModel.count / 2)
                }

                pathView.currentIndex = matchedIndex
                updateBackground()
            }
        }

        Connections {
            target: folderModel
            function onCountChanged() {
                initTimer.restart()
            }
        }

        function activateCurrent() {
            const path = folderModel.get(pathView.currentIndex, "filePath");
            Quickshell.execDetached(["bash", Quickshell.shellPath("commands.sh"), path]);
            Qt.quit();
        }

        path: Path {
            startX: -main.width * 0.12
            startY: main.height - 180

            PathAttribute { name: "itemScale"; value: 1.0 }
            PathAttribute { name: "itemOpacity"; value: 0.95 }
            PathAttribute { name: "itemZ"; value: 1 }
            PathPercent { value: 0.0 }

            PathLine { x: main.width * 0.5; y: main.height - 180 }
            PathAttribute { name: "itemScale"; value: 1.30 }
            PathAttribute { name: "itemOpacity"; value: 1.0 }
            PathAttribute { name: "itemZ"; value: 100 }
            PathPercent { value: 0.5 }

            PathLine { x: main.width * 1.12; y: main.height - 180 }
            PathAttribute { name: "itemScale"; value: 1.0 }
            PathAttribute { name: "itemOpacity"; value: 0.95 }
            PathAttribute { name: "itemZ"; value: 1 }
            PathPercent { value: 1.0 }
        }

        delegate: Item {
            id: delegateItem
            width: 340
            height: 215

            property bool isCurrent: PathView.isCurrentItem
            // Bind through model.fileName so this stays in sync across
            // delegate recycling inside PathView.
            property bool isVideo: main.isVideoFile(model.fileName)

            scale: PathView.itemScale
            opacity: PathView.itemOpacity
            z: isCurrent ? 100 : PathView.itemZ

            transform: Matrix4x4 {
                matrix: Qt.matrix4x4(
                    1, -0.22, 0, 0.22 * 215 / 2,
                    0, 1, 0, 0,
                    0, 0, 1, 0,
                    0, 0, 0, 1
                )
            }

            Item {
                anchors.fill: parent

                // Inner mask shape defining the curved corners.
                Rectangle {
                    id: mask
                    anchors.fill: parent
                    radius: 14
                    visible: false
                }

                // Card content: image/video thumbnail. Kept hidden because
                // it is used as the OpacityMask source. No overlays live in
                // here — anything that needs a runtime visible binding must
                // stay outside the ShaderEffectSource tree.
                Rectangle {
                    id: cardContent
                    anchors.fill: parent
                    color: "#1e1e2e"
                    visible: false

                    Text {
                        id: alt
                        text: "Loading..."
                        color: configs.border_color
                        anchors.centerIn: parent
                        font.pixelSize: 14
                        visible: img.status !== Image.Ready
                    }

                    Image {
                        id: img
                        anchors.fill: parent
                        fillMode: Image.PreserveAspectCrop
                        asynchronous: true
                        cache: false
                        smooth: true

                        source: main.getThumbnailSource(fileName)
                        sourceSize.width: width
                        sourceSize.height: height

                        Timer {
                            id: retryTimer
                            interval: 1000
                            repeat: false
                            onTriggered: {
                                let s = img.source;
                                img.source = "";
                                img.source = s;
                            }
                        }

                        onStatusChanged: {
                            if (status === Image.Ready) {
                                alt.text = "";
                            } else if (status === Image.Error) {
                                alt.text = "Caching";
                                retryTimer.start();
                            }
                        }
                    }
                }

                // Clipped rounded card result.
                OpacityMask {
                    anchors.fill: parent
                    source: cardContent
                    maskSource: mask
                }

                // VIDEO badge — outside cardContent so its visible binding
                // is honoured normally, above the masked image.
                Rectangle {
                    anchors.top: parent.top
                    anchors.left: parent.left
                    anchors.margins: 10
                    width: 46
                    height: 18
                    radius: 4
                    color: "#cc000000"
                    border.width: 1
                    border.color: "#44ffffff"
                    z: 20
                    visible: delegateItem.isVideo && img.status === Image.Ready

                    Text {
                        anchors.centerIn: parent
                        text: "VIDEO"
                        color: "#ff6666"
                        font.pixelSize: 9
                        font.weight: Font.Bold
                        font.letterSpacing: 1
                    }
                }

                Rectangle {
                    id: selectedBorder
                    anchors.fill: parent
                    radius: 14
                    color: "transparent"
                    antialiasing: true
                    border.width: delegateItem.isCurrent ? 2 : 1
                    border.color: delegateItem.isCurrent
                        ? (configs.border_color.length > 0 ? configs.border_color : "#e6e6e6")
                        : "#33ffffff"
                }
            }

            MouseArea {
                anchors.fill: parent
                onClicked: {
                    pathView.forceActiveFocus();
                    if (pathView.currentIndex === index) {
                        pathView.activateCurrent();
                    } else {
                        pathView.currentIndex = index;
                    }
                }
            }
        }

        Keys.onPressed: function (event) {
            const big = configs.number_of_pictures > 0 ? configs.number_of_pictures : 5;

            if (event.key === Qt.Key_L || event.key === Qt.Key_Right) {
                pathView.incrementCurrentIndex();
            } else if (event.key === Qt.Key_H || event.key === Qt.Key_Left) {
                pathView.decrementCurrentIndex();
            } else if (event.key === Qt.Key_U) {
                for (let i = 0; i < big; i++) pathView.incrementCurrentIndex();
            } else if (event.key === Qt.Key_D) {
                for (let i = 0; i < big; i++) pathView.decrementCurrentIndex();
            } else if (event.key === Qt.Key_Space || event.key === Qt.Key_Return) {
                pathView.activateCurrent();
            } else if (event.key === Qt.Key_Escape) {
                Qt.quit();
            } else {
                return;
            }
            event.accepted = true;
        }
    }
}
